# Generated by Django 5.0.4 on 2024-11-12 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('indicator', models.CharField(blank=True, max_length=500, null=True)),
                ('initial', models.CharField(max_length=45)),
                ('annual_plan', models.CharField(max_length=45)),
                ('first_quarter_plan', models.CharField(max_length=45)),
                ('second_quarter_plan', models.CharField(max_length=45)),
                ('third_quarter_plan', models.CharField(max_length=45)),
                ('fourth_quarter_plan', models.CharField(max_length=45)),
                ('first_quarter_performance', models.CharField(blank=True, max_length=45, null=True)),
                ('second_quarter_performance', models.CharField(blank=True, max_length=45, null=True)),
                ('third_quarter_performance', models.CharField(blank=True, max_length=45, null=True)),
                ('fourth_quarter_performance', models.CharField(blank=True, max_length=45, null=True)),
                ('performance_in_percent', models.CharField(blank=True, max_length=45, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('operation', models.CharField(choices=[('sum', 'SUM'), ('average', 'AVERAGE')], default='sum', max_length=45)),
                ('is_approved', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=45)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_outcome', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=45)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(null=True)),
                ('quarter', models.PositiveSmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False, help_text='Indicates if the plan document is approved by its sector.', verbose_name='Approval Status')),
                ('submitted', models.BooleanField(default=False, help_text='Indicates if the plan document is submitted.', verbose_name='Submition Status')),
                ('late', models.BooleanField(default=False, help_text='This will indicate if the user subitted the document late or not.', verbose_name='On time status')),
            ],
        ),
        migrations.CreateModel(
            name='PlanNarration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('መግቢያ', 'መግቢያ'), ('የልማት ዕቅዱ እንድምታዎች እና የሚጠበቁ ውጤቶች', 'የልማት ዕቅዱ እንድምታዎች እና የሚጠበቁ ውጤቶች'), ('የበጀት ዓመት ኢላማዎችና የድርጊት መርሃ ግብር', 'የበጀት ዓመት ኢላማዎችና የድርጊት መርሃ ግብር'), ('የበጀት ዓመቱን የልማት ዕቅድ ለማሰካት የሚተገበሩ ማስፈጸሚያዎች', 'የበጀት ዓመቱን የልማት ዕቅድ ለማሰካት የሚተገበሩ ማስፈጸሚያዎች')], max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planphotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.FileField(blank=True, null=True, upload_to='plandoc/files')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
