# Generated by Django 5.0.4 on 2024-11-12 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planApp', '0001_initial'),
        ('reportApp', '0001_initial'),
        ('userApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_kpis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_kpis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='division_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.division'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='measure_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportApp.measure'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='monitoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.monitoring'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='sector_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.sector'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_kpis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_main_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_main_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='division_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.division'),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='monitoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.monitoring'),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='sector_id',
            field=models.ManyToManyField(blank=True, null=True, to='userApp.sector'),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_main_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='main_goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='planApp.maingoal'),
        ),
        migrations.AddField(
            model_name='plandocument',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plandocument',
            name='division_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.division'),
        ),
        migrations.AddField(
            model_name='plandocument',
            name='monitoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.monitoring'),
        ),
        migrations.AddField(
            model_name='plandocument',
            name='sector_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.sector'),
        ),
        migrations.AddField(
            model_name='plannarration',
            name='plan_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_narrations', to='planApp.plandocument'),
        ),
        migrations.AddField(
            model_name='planphotos',
            name='plan_narration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Plan_photos', to='planApp.plannarration'),
        ),
        migrations.AddField(
            model_name='strategicgoal',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_strategic_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategicgoal',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_strategic_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategicgoal',
            name='sector_id',
            field=models.ManyToManyField(blank=True, to='userApp.sector'),
        ),
        migrations.AddField(
            model_name='strategicgoal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_strategic_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='strategic_goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maingoals', to='planApp.strategicgoal'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='plan_narration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='planApp.plannarration'),
        ),
        migrations.AddField(
            model_name='planphotos',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Plan_photos', to='planApp.subtitle'),
        ),
    ]
