# Generated by Django 5.0.8 on 2025-02-07 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp', '0002_initial'),
        ('reportApp', '0003_remove_measure_type_alter_measure_id_unit'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='annual_plan',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='first_quarter_performance',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='first_quarter_plan',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='fourth_quarter_performance',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='fourth_quarter_plan',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='initial',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='measure_id',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='monitoring_id',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='performance_in_percent',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='second_quarter_performance',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='second_quarter_plan',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='sector_id',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='third_quarter_performance',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='third_quarter_plan',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='division_id',
        ),
        migrations.AlterField(
            model_name='maingoal',
            name='sector_id',
            field=models.ManyToManyField(blank=True, to='userApp.sector'),
        ),
        migrations.CreateModel(
            name='AnnualKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual', models.FloatField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('initial', models.FloatField()),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('pl1', models.FloatField()),
                ('pl2', models.FloatField()),
                ('pl3', models.FloatField()),
                ('pl4', models.FloatField()),
                ('pr1', models.FloatField(blank=True, null=True)),
                ('pr2', models.FloatField(blank=True, null=True)),
                ('pr3', models.FloatField(blank=True, null=True)),
                ('pr4', models.FloatField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('sum', 'SUM'), ('average', 'AVERAGE')], default='sum', max_length=45)),
                ('annual_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportApp.unit')),
                ('division_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.division')),
                ('initial_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_unit', to='reportApp.unit')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planApp.kpi')),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportApp.measure')),
                ('pl1_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl1_unit', to='reportApp.unit')),
                ('pl2_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl2_unit', to='reportApp.unit')),
                ('pl3_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl3_unit', to='reportApp.unit')),
                ('pl4_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl4_unit', to='reportApp.unit')),
                ('pr1_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr1_unit', to='reportApp.unit')),
                ('pr2_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr2_unit', to='reportApp.unit')),
                ('pr3_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr3_unit', to='reportApp.unit')),
                ('pr4_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr4_unit', to='reportApp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeyearKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_one', models.PositiveIntegerField(blank=True, null=True)),
                ('year_one_value', models.CharField(max_length=100, null=True)),
                ('year_two', models.PositiveIntegerField(blank=True, null=True)),
                ('year_two_value', models.CharField(max_length=100, null=True)),
                ('year_three', models.PositiveIntegerField(blank=True, null=True)),
                ('year_three_value', models.CharField(max_length=100, null=True)),
                ('division_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.division')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planApp.kpi')),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportApp.measure')),
                ('year_one_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_one_units', to='reportApp.unit')),
                ('year_three_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_three_units', to='reportApp.unit')),
                ('year_two_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_two_units', to='reportApp.unit')),
            ],
        ),
        migrations.AddField(
            model_name='kpi',
            name='division_id',
            field=models.ManyToManyField(blank=True, related_name='kpis', to='userApp.division'),
        ),
    ]
