# Generated by Django 5.0.8 on 2025-09-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp', '0003_remove_kpi_added_by_remove_kpi_annual_plan_and_more'),
        ('reportApp', '0003_remove_measure_type_alter_measure_id_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='year',
        ),
        migrations.AddField(
            model_name='annualkpi',
            name='incremental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='initial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='initial_unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threeyear_kpis', to='reportApp.unit'),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='operation',
            field=models.CharField(choices=[('sum', 'SUM'), ('average', 'AVERAGE')], default='sum', max_length=45),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='three_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='three_year_unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportApp.unit'),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='year_one_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='year_one_performance_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_one_performance_units', to='reportApp.unit'),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='year_three_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='year_three_performance_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_three_performance_units', to='reportApp.unit'),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='year_two_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threeyearkpi',
            name='year_two_performance_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_two_performance_units', to='reportApp.unit'),
        ),
        migrations.AlterField(
            model_name='annualkpi',
            name='kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annualkpi_set', to='planApp.kpi'),
        ),
        migrations.AlterField(
            model_name='annualkpi',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maingoal',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threeyearkpi',
            name='kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threeyear_kpi_set', to='planApp.kpi'),
        ),
        migrations.AlterField(
            model_name='threeyearkpi',
            name='year_one_value',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='threeyearkpi',
            name='year_three_value',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='threeyearkpi',
            name='year_two_value',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
