"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import sys
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

os.environ['PYTHONIOENCODING'] = "utf-8"
sys.stdout.reconfigure(encoding="utf-8")
ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'userApp.User'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Adjust the number as per your application's needs

X_FRAME_OPTIONS = "SAMEORIGIN"
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024 # 20 Mb limit
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd jango-insecure-g7@42%--)e_drvsd##kgyq9v%zxj_0t^b&ji1ye9^!%bqa8g@-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# Application definition

INSTALLED_APPS = [
    'channels',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third party libraries
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'debug_toolbar',
    'django.contrib.humanize',


    'userApp.apps.UserappConfig',
    'roleApp.apps.RoleappConfig',
    'planApp.apps.PlanappConfig',
    'reportApp.apps.ReportappConfig',
    'comApp.apps.ComappConfig',
    'monApp.apps.MonappConfig', 
    'django_prometheus', 
    'mozilla_django_oidc',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),  # Change this to your desired expiration time
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # Change this to your desired refresh token expiration time
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 'DEFAULT_ROUTER_TRAILING_SLASH': False,
}


AUTHENTICATION_BACKENDS = [
    'userApp.backends.EmailBackend',  # Replace `your_app_name` with your app's name
    'django.contrib.auth.backends.ModelBackend',  # Default backend (optional)
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',      
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware', 


]
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "pmo_db"),
        "USER": os.getenv("POSTGRES_USER", "pmo_user"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "pmo_pass"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": os.getenv("POSTGRES_PORT", 5432),
    }
}






CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

import os
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# MEDIA_URL = '/assets/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Define the URL prefix for media files
MEDIA_URL = '/media/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static/')
# ]

# MEDIA_ROOT = os.path.join(BASE_DIR, 'static/assets')
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://192.168.1.243:3001",
#     "http://192.168.1.243:3002",
#     "http://192.168.1.243:3003",
#     "http://192.168.1.243:3003",
#     "http://192.168.1.243:3004",
#     "http://192.168.1.243:5173",
#     "http://localhost:5174",
    
# ]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'csolve12022@gmail.com'
EMAIL_HOST_PASSWORD = 'ripu pmpo yzic gpjs'

# keycloak config

KEYCLOAK_CLIENT_ID = "PRMS"
KEYCLOAK_CLIENT_SECRET = "fg1ERTmny3RAWr6wgnVCveSBTxOJAZKe"
KEYCLOAK_REDIRECT_URI = "https://192.168.8.72:8001/"
KEYCLOAK_BASE_URL = "https://192.168.8.135:8081/"
KEYCLOAK_REALM = "pmo-realm"
PORTAL_BASE_URL = "https://192.168.8.135:8001/"

APPEND_SLASH = False

OIDC_RP_CLIENT_ID = "django-backend"
OIDC_RP_CLIENT_SECRET = "<secret-from-keycloak>"
OIDC_OP_AUTHORIZATION_ENDPOINT = "http://172.18.6.64/:8081/realms/myrealm/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = "http://172.18.6.64/:8081/realms/myrealm/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = "http://172.18.6.64/:8081/realms/myrealm/protocol/openid-connect/userinfo"

LOGIN_URL = '/oidc/authenticate/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
