# Generated by Django 5.0.4 on 2024-11-12 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportApp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsummary',
            name='division_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_summaryreport', to='userApp.division'),
        ),
        migrations.AddField(
            model_name='reportsummary',
            name='monitoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_summaryreport', to='userApp.monitoring'),
        ),
        migrations.AddField(
            model_name='reportsummary',
            name='sector_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_summaryreport', to='userApp.sector'),
        ),
        migrations.AddField(
            model_name='summary',
            name='division_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_summary', to='userApp.division'),
        ),
        migrations.AddField(
            model_name='summary',
            name='monitoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_summary', to='userApp.monitoring'),
        ),
        migrations.AddField(
            model_name='summary',
            name='sector_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_summary', to='userApp.sector'),
        ),
        migrations.AddField(
            model_name='summaryfiles',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_files', to='reportApp.summary'),
        ),
        migrations.AddField(
            model_name='summarysubtitle',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_subtitle', to='reportApp.summary'),
        ),
        migrations.AddField(
            model_name='subtitlefiles',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_photo', to='reportApp.summarysubtitle'),
        ),
    ]
