# Generated by Django 5.0.8 on 2025-02-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='type',
        ),
        migrations.AlterField(
            model_name='measure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('symbol', models.CharField(max_length=10)),
                ('conversionFactor', models.CharField(max_length=45)),
                ('isBaseUnit', models.BooleanField(default=0)),
                ('measure_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='reportApp.measure')),
            ],
        ),
    ]
