# Generated by Django 5.0.8 on 2025-09-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp', '0004_remove_kpi_weight_remove_strategicgoal_year_and_more'),
        ('reportApp', '0003_remove_measure_type_alter_measure_id_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpidescription',
            name='kpi_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpidescription', to='planApp.annualkpi'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='conversionFactor',
            field=models.FloatField(max_length=45),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
